import { afterEach, describe, expect, spyOn, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateNotices, runNoticesCli } from "../../../tools/third-party-notices";

const root = join(import.meta.dir, "../../../..");
const noticesPath = join(root, "THIRD_PARTY_NOTICES.txt");

function pkgVersion(name: string): string {
  return (JSON.parse(readFileSync(join(root, "node_modules", name, "package.json"), "utf8")) as { version: string })
    .version;
}

/**
 * THIRD_PARTY_NOTICES.txt is committed at the repo root and regenerated by
 * `bun run src/tools/third-party-notices.ts` whenever the bundled dependency
 * set changes; `--check` fails when the committed file drifts from that.
 */
describe("THIRD_PARTY_NOTICES.txt", () => {
  test("exists and is non-empty", () => {
    expect(statSync(noticesPath).size).toBeGreaterThan(0);
  });

  test("lists commander and chargebee with the versions installed in node_modules", () => {
    const content = readFileSync(noticesPath, "utf8");
    expect(content).toContain(`commander@${pkgVersion("commander")}`);
    expect(content).toContain(`chargebee@${pkgVersion("chargebee")}`);
  });

  test("is byte-identical across two generations", async () => {
    const first = await generateNotices();
    const second = await generateNotices();
    expect(first).toBe(second);
  });

  test("--check passes against the committed file", () => {
    const result = spawnSync("bun", ["run", "src/tools/third-party-notices.ts", "--check"], {
      cwd: root,
      encoding: "utf8",
    });
    expect(result.status).toBe(0);
  });

  test("package.json files includes THIRD_PARTY_NOTICES.txt", () => {
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { files: string[] };
    expect(pkg.files).toContain("THIRD_PARTY_NOTICES.txt");
  });
});

describe("runNoticesCli", () => {
  const fake = async () => "FAKE NOTICES\n";
  let dir: string | undefined;
  let logSpy: ReturnType<typeof spyOn>;
  let errorSpy: ReturnType<typeof spyOn>;
  let exitSpy: ReturnType<typeof spyOn>;

  afterEach(() => {
    logSpy?.mockRestore();
    errorSpy?.mockRestore();
    exitSpy?.mockRestore();
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  test("writes --out", async () => {
    dir = mkdtempSync(join(tmpdir(), "cb-notices-"));
    const out = join(dir, "THIRD_PARTY_NOTICES.txt");
    logSpy = spyOn(console, "log").mockImplementation(() => {});
    await runNoticesCli(["--out", out], fake);
    expect(readFileSync(out, "utf-8")).toBe("FAKE NOTICES\n");
    expect(String(logSpy.mock.calls[0]?.[0])).toContain("Wrote");
  });

  test("--check passes when the file matches", async () => {
    dir = mkdtempSync(join(tmpdir(), "cb-notices-check-"));
    const out = join(dir, "THIRD_PARTY_NOTICES.txt");
    writeFileSync(out, "FAKE NOTICES\n");
    logSpy = spyOn(console, "log").mockImplementation(() => {});
    await runNoticesCli(["--check", "--out", out], fake);
    expect(String(logSpy.mock.calls[0]?.[0])).toContain("up to date");
  });

  test("--check exits 1 when the file is missing or stale", async () => {
    dir = mkdtempSync(join(tmpdir(), "cb-notices-stale-"));
    const out = join(dir, "missing.txt");
    errorSpy = spyOn(console, "error").mockImplementation(() => {});
    exitSpy = spyOn(process, "exit").mockImplementation((() => {
      throw new Error("exit 1");
    }) as never);
    await expect(runNoticesCli(["--check", "--out", out], fake)).rejects.toThrow(/exit 1/);
    expect(String(errorSpy.mock.calls[0]?.[0])).toContain("out of date");
  });

  test("--out requires a path argument", async () => {
    await expect(runNoticesCli(["--out"], fake)).rejects.toThrow(/--out requires a path argument/);
  });
});

describe("generateNotices bundle failures", () => {
  afterEach(() => {
    // bun:test restores spies automatically after each test when created in-test
  });

  test("throws when Bun.build fails", async () => {
    const buildSpy = spyOn(Bun, "build").mockResolvedValue({
      success: false,
      logs: ["boom"],
    } as never);
    try {
      const errorSpy = spyOn(console, "error").mockImplementation(() => {});
      await expect(generateNotices()).rejects.toThrow(/bundling src\/index.ts failed/);
      errorSpy.mockRestore();
    } finally {
      buildSpy.mockRestore();
    }
  });

  test("throws when Bun.build omits a metafile", async () => {
    const buildSpy = spyOn(Bun, "build").mockResolvedValue({
      success: true,
      logs: [],
    } as never);
    try {
      await expect(generateNotices()).rejects.toThrow(/did not return a metafile/);
    } finally {
      buildSpy.mockRestore();
    }
  });
});
